### ISSUE TITLE
TTLRemover do not compile with Cassandra 2.2

### ISSUE THREAD

**Issue by farumi** [instaclustr/TTLRemover#1]
Hello,

Very useful and instructive piece of software, thank you to share.

Anyway, I've followed the instructions on the Readme, but it didn't compile:
```
    [javac] /home/ferran/TTLRemover/cassandra-2.2-src/src/java/org/apache/cassandra/noTTL/NoTTLReader.java:1958: error: cannot find symbol
    [javac]         return sstableMetadata.replayPosition;
    [javac]                               ^
    [javac]   symbol:   variable replayPosition
    [javac]   location: variable sstableMetadata of type StatsMetadata
```
And compiler is right, this variable do not exist... on 2.2 (but it exists on 1.6)

To quickly solve the issue I've just deleted the code calling this (`noTTL/NoTTLReader.java:1958`):
```java
    public ReplayPosition getReplayPosition()
    {
        return sstableMetadata.replayPosition;
    }
```
And it works!
